format_ocsp_request: fix double encoding of the nonce
The nonce should not be in 2 `core.OctetString`. Otherwise, when comparing the nonce received from the OCSP server, they don't match:
```
pyhanko_certvalidator.errors.OCSPValidationError: Unable to verify OCSP response since the request b'\x04\x10\xc3\xf9\x98\xaf\xe6\xd7\xf8v\xdfQ\xae\xac\x80B\x00!' and response b'\xc3\xf9\x98\xaf\xe6\xd7\xf8v\xdfQ\xae\xac\x80B\x00!' nonces do not match
```

Note the "Request nonce" starts with `\x04\x10` , that are not present in the "Response nonce".